name: Continuous Integration Workflow

on: push

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: set environment variables
        run: |
          echo "::set-env name=OUT_DIR::dist"

      - name: checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: install dependencies
        run: yarn install

      - name: lint
        run: yarn lint

      - name: production build
        run: yarn build
