name: Release Workflow

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: set environment variables
        run: |
          echo "::set-env name=OUT_DIR::build"

      - name: checkout
        uses: actions/checkout@v2

      - name: install dependencies
        run: yarn install

      - name: test
        run: yarn test

      - name: production build
        run: |
          yarn build
          touch ${{ env.OUT_DIR }}/.nojekyll

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: buid-artifacts
          path: ${{ env.OUT_DIR }}

  publish:
    needs: test-and-build
    runs-on: ubuntu-latest

    steps:
      - name: set environment variables
        run: |
          echo "::set-env name=OUT_DIR::build"

      - name: checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: download artifacts
        uses: actions/download-artifact@v2
        with:
          name: buid-artifacts
          path: ${{ env.OUT_DIR }}

      - name: publish
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: release
          FOLDER: ${{ env.OUT_DIR }}
          CLEAN: true
